### ISSUE TITLE
ALL ACCEPTABLE BYS are 'social- worse'

### ISSUE THREAD

**Issue by icejag** [Display-Lab/precision-feedback-pipeline#162]
Mark did a stress test for more than 12000 records and Display LAB team did the test against leakdown tester with mark's sample input for 60 records and all input messages are returning 'Social worse' causal-pathway. Get one test case where the output must return another causal pathway but returns a social worse instead.

**Comment by mackgalante** [comment]
Current resolution strategy is making changes to bitstomach to exclude performance data that cannot be reasonably considered statistically significant, secondary changes may be to alter gap size considerations for negative gaps. Both changes would increase variability in selected causal pathways.

### Task list

Priority 1: Pilot implementation
- [ ] New bitstomach function to clean performance dataframe as first pipeline step
    - [ ] define function
    - [ ] remove measures where 'denominator' < 15
        - [ ] Remove measure as a whole from the dataframe
        - [ ] Keep cleaned measure in JSON serialization for inclusion in output message back to MPOG (may or may not be necessary for study)
    - [ ] Test, verify processing otherwise intact after implementation
    
Priority 2: Eventual implementation/design review potentially required
 - [ ] Alterations to Esteemer
     - [ ] Both positive and negative gaps should probably select from the smallest available gap, not largest
     - This prevents gaps from being over-emphasized when performance is excessively far from a comparator, may be better for feedback anyway as more actionable for recipient?
     - Further design review as a team probably needed here, best to leave for the post-pilot

**Comment by mackgalante** [comment]
Decided to move back down to 10 as the denominator, just to keep failing requests to a minimum before cleaner error handling is written. Considering CLT t test sample is generally 30, lowering it will lower our statistical power but ten seems like a good compromise.


This still isn't pushing us towards more social better messages being selected, something else is happening to force the rank towards measures with social worse. See the following case with synthetic data:
```zsh
INFO:     127.0.0.1:59124 - "POST /createprecisionfeedback/ HTTP/1.1" 200 OK
CRITICAL:root: reading graph--- 0.003003835678100586 seconds ---
CRITICAL:root: reading graph--- 0.0283050537109375 seconds ---
INFO|  Calling BitStomach from main...
DEBUG|  Running bit_stomach.student_t_cleaner...
DEBUG|  Found rows with non-significant denominators, attempting removal...
DEBUG|  Cleaned dataframe is: 
0  staff_number measure       month passed_count flagged_count denominator peer_average_comparator peer_75th_percentile_benchmark peer_90th_percentile_benchmark MPOG_goal
12            3    BP02  2022-09-01           16             0          16                    81.7                          100.0                          100.0      90.0
13            3    BP02  2022-10-01           12             0          12                    82.3                          100.0                          100.0      90.0
14            3    BP02  2022-11-01           18             0          18                    82.4                          100.0                          100.0      90.0
15            3    BP02  2022-12-01           18             2          20                    83.0                          100.0                          100.0      90.0
16            3    BP02  2023-01-01           16             0          16                    83.0                          100.0                          100.0      90.0
17            3    BP02  2023-02-01           18             0          18                    83.3                          100.0                          100.0      90.0
18            3    BP02  2023-03-01           30             0          30                    83.6                          100.0                          100.0      90.0
19            3    BP02  2023-04-01           14             2          16                    84.7                          100.0                          100.0      90.0
20            3    BP02  2023-05-01           34             1          35                    84.5                          100.0                          100.0      90.0
21            3    BP02  2023-06-01           34             4          38                    84.8                          100.0                          100.0      90.0
22            3    BP02  2023-07-01           49             1          50                    84.6                          100.0                          100.0      90.0
23            3    BP02  2023-08-01           39             0          39                    84.9                          100.0                          100.0      90.0
38            3   NMB02  2023-07-01           10             0          10                    84.6                          100.0                          100.0      90.0
60            3   SUS02  2022-09-01            5             7          12                    81.7                          100.0                          100.0      90.0
62            3   SUS02  2022-11-01            8             8          16                    82.4                          100.0                          100.0      90.0
64            3   SUS02  2023-01-01            2            11          13                    83.0                          100.0                          100.0      90.0
65            3   SUS02  2023-02-01            8             2          10                    83.3                          100.0                          100.0      90.0
66            3   SUS02  2023-03-01            8            11          19                    83.6                          100.0                          100.0      90.0
67            3   SUS02  2023-04-01            2            11          13                    84.7                          100.0                          100.0      90.0
68            3   SUS02  2023-05-01           10             9          19                    84.5                          100.0                          100.0      90.0
69            3   SUS02  2023-06-01            9            16          25                    84.8                          100.0                          100.0      90.0
70            3   SUS02  2023-07-01           15            16          31                    84.6                          100.0                          100.0      90.0
71            3   SUS02  2023-08-01            8            12          20                    84.9                          100.0                          100.0      90.0
INFO|  Calling CandidateSmasher from main...
WARNING:rdflib.term:Display compatibility does not look like a valid URI, trying to serialize this will break.
INFO|  Calling ThinkPudding from main...
CRITICAL:root: reading spek graph--- 3.0994415283203125e-06 seconds ---
CRITICAL:root: reading causal pathways graph--- 1.9073486328125e-06 seconds ---
CRITICAL:root: processing causal pathways--- 0.00026702880859375 seconds ---
CRITICAL:root: processing spek_cs--- 0.0010709762573242188 seconds ---
CRITICAL:root: processing matching--- 0.00011706352233886719 seconds ---
CRITICAL:root: inserting acceptable by--- 0.00011420249938964844 seconds ---
INFO|  Calling Esteemer from main...
INFO|  Calling Pictoralist from main...
INFO|  Data gap(s) detected, filling voids...
...
DEBUG|  Requested 6 month display, dataframe has 12 months
INFO|  Generating line graph from performance data...
DEBUG|  Running 'plot_and_save'...
DEBUG|  Running pictoralist/prepare_selected_message...
0       month measure passed_count denominator  performance_level comparator_level  goal_percent
0  2022-09-01   SUS02            5          12          41.666667            100.0          90.0
1  2022-10-01   SUS02          NaN         NaN                NaN              NaN          90.0
2  2022-11-01   SUS02            8          16          50.000000            100.0          90.0
3  2022-12-01   SUS02          NaN         NaN                NaN              NaN          90.0
4  2023-01-01   SUS02            2          13          15.384615            100.0          90.0
5  2023-02-01   SUS02            8          10          80.000000            100.0          90.0
6  2023-03-01   SUS02            8          19          42.105263            100.0          90.0
7  2023-04-01   SUS02            2          13          15.384615            100.0          90.0
8  2023-05-01   SUS02           10          19          52.631579            100.0          90.0
9  2023-06-01   SUS02            9          25          36.000000            100.0          90.0
10 2023-07-01   SUS02           15          31          48.387097            100.0          90.0
11 2023-08-01   SUS02            8          20          40.000000            100.0          90.0
INFO:     127.0.0.1:59125 - "POST /createprecisionfeedback/ HTTP/1.1" 200 OK
```

As we can see, we could be getting a valid social better over the peer average, but Esteemer really likes telling people they are below the 90th percentile. And I mean really likes it, as in the entire first set of data that isn't synthetic from MPOG had 0/60 requests that were not Social worse about the Peer top 10% benchmark.

Separate issue likely needed for this.

**Comment by mackgalante** [comment]
Added cleaning function to remove the worst data from consideration, but that doesn't solve the issue of social worse to peer 90th benchmark being the only candidate used in feedback messages.

**Comment by pboisver** [comment]
Closing as addressed for now. PFP is not currently selecting the new (equivalent message); existing "not a top performer" message is generally/always selected as a byproduct of current _first available_ rule when multiple messages have equivalent score. Will plan further refinements to be implemented after first production run.

**Comment by zachll** [comment]
Adding the new message template - opportunity to improve top 10 - did not result in its selection at any point during testing.

Esteemer is consistently choosing the message "you are not a top performer" and the reasons for that are not yet clear, whether it is a result of a blank node appearing first, or alphabetical order because "n" comes before "o" in the file names.
